# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Contains all languages supported by Microsoft Translate 
# as of February 2014

Language.create(name: "Arabic", code: "ar")
Language.create(name: "Bosnian (Latin)", code: "bs-Latn")
Language.create(name: "Bulgarian", code: "bg")
Language.create(name: "Catalan", code: "ca")
Language.create(name: "Chinese Simplified", code: "zh-CHS")
Language.create(name: "Chinese Traditional", code: "zh-CHT")
Language.create(name: "Croatian", code: "hr")
Language.create(name: "Czech", code: "cs")
Language.create(name: "Danish", code: "da")
Language.create(name: "Dutch", code: "nl")
Language.create(name: "English", code: "en")
Language.create(name: "Estonian", code: "et")
Language.create(name: "Finnish", code: "fi")
Language.create(name: "French", code: "fr")
Language.create(name: "German", code: "de")
Language.create(name: "Greek", code: "el")
Language.create(name: "Haitian Creole", code: "ht")
Language.create(name: "Hebrew", code: "he")
Language.create(name: "Hindi", code: "hi")
Language.create(name: "Hmong Daw", code: "mww")
Language.create(name: "Hungarian", code: "hu")
Language.create(name: "Indonesian", code: "id")
Language.create(name: "Italian", code: "it")
Language.create(name: "Japanese", code: "ja")
Language.create(name: "Klingon", code: "tlh")
Language.create(name: "Klingon (pIqaD)", code: "tlh-Qaak")
Language.create(name: "Korean", code: "ko")
Language.create(name: "Latvian", code: "lv")
Language.create(name: "Lithuanian", code: "lt")
Language.create(name: "Malay", code: "ms")
Language.create(name: "Maltese", code: "mt")
Language.create(name: "Norwegian", code: "no")
Language.create(name: "Persian", code: "fa")
Language.create(name: "Polish", code: "pl")
Language.create(name: "Portuguese", code: "pt")
Language.create(name: "Querétaro Otomi", code: "otq")
Language.create(name: "Romanian", code: "ro")
Language.create(name: "Russian", code: "ru")
Language.create(name: "Serbian (Cyrillic)", code: "sr-Cyrl")
Language.create(name: "Serbian (Latin)", code: "sr-Latn")
Language.create(name: "Slovak", code: "sk")
Language.create(name: "Slovenian", code: "sl")
Language.create(name: "Spanish", code: "es")
Language.create(name: "Swedish", code: "sv")
Language.create(name: "Thai", code: "th")
Language.create(name: "Turkish", code: "tr")
Language.create(name: "Ukrainian", code: "uk")
Language.create(name: "Urdu", code: "ur")
Language.create(name: "Vietnamese", code: "vi")
Language.create(name: "Welsh", code: "cy")
Language.create(name: "Yucatec Maya", code: "yua")
